#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


#Layout
yabai -m config layout bsp

#Specify whether managed windows should become the first or second leaf-node.
yabai -m config window_placement second_child

#Paddings
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20


#Mouse settings

yabai -m config mouse_modifier alt
## move
yabai -m config mouse_action1 move
## resize
yabai -m config mouse_action2 resize
## Swap windows
yabai -m config mouse_drop_action swap


# Other

# Disabled apps
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app=Finder manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Code Whisperer$" manage=off

# osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'


echo "yabai configuration loaded..
